### ISSUE TITLE
Unit Testing discussion

### ISSUE THREAD

**Issue by cravend** [SCCapstone/DKMS#122]
We're using [Cypress](https://www.cypress.io) for our testing. It can do both E2E and individual component testing. It seems that E2E = behavior testing for the testing milestone, but is a component test equal to "unit testing"? We've written an (extremely basic) component test to see if a component renders, visible [here](https://github.com/SCCapstone/DKMS/blob/main/components/ui/UsernameLink.cy.tsx). Is this the right track for unit testing (but with more assertions)?

**Comment by josemvidal** [comment]
Unit tests call actual functions (that you wrote) in your code. So, if you wrote a `formatPayment(int) -> string` function then the unit test calls it directly and checks that it does format things the way you wanted it to (4 -> "$4.00", -1 -> "", etc.)

I don't know if Cypress can do that. Your test code needs to be able to call your program code.

**Comment by cravend** [comment]
Got it, thank you!
