### ISSUE TITLE
Posts from un-followed still show up in feed

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/DKMS#167]
I unfollow them but the posts are still in feed:

https://user-images.githubusercontent.com/228704/222172724-24a10f2a-9177-421e-8d1f-47af626bfc02.mp4

**Comment by cravend** [comment]
This is expected behavior — at this time, we wanted the feed to be global. We plan to make a filter to flip between "global" and "following-only views" soon.

However, if you think that it makes more sense to flip them (i.e. have the feed be "following only"), we can do that.

**Comment by josemvidal** [comment]
Yes, I assumed Feed was the ones I Follow.

Adding a filter (Everyone, Followed) at the top would make it easy to see what is going on.
