### ISSUE TITLE
Posts dont work

### ISSUE THREAD

**Issue by JPSharp** [SCCapstone/DKMS#198]
https://user-images.githubusercontent.com/44646798/222816598-a9fbdfc7-2385-411e-a614-f8dcc95dbec2.mp4

**Comment by cravend** [comment]
We're looking into this... Dr. Vidal was able to make some posts (he's the one with the smiley face) so I'm not sure what broke between then and now.

**Comment by cravend** [comment]
Will be fixed by #206
