### ISSUE TITLE
fix: design errors

### ISSUE THREAD

**Issue by sophiecra** [SCCapstone/DKMS#314]

**Comment by sophiecra** [comment]
<img width="1325" alt="Screen Shot 2023-04-02 at 11 52 06 PM" src="https://user-images.githubusercontent.com/77420992/229407518-bd307c47-4e2e-4388-9e3b-c232fa31ad46.png">

Overflowing tables

**Comment by sophiecra** [comment]
<img width="358" alt="Screen Shot 2023-04-02 at 11 59 07 PM" src="https://user-images.githubusercontent.com/77420992/229408298-f862b4b8-517e-4468-98a7-fb84a58c2955.png">
Spacing

**Comment by sophiecra** [comment]
<img width="393" alt="Screen Shot 2023-04-02 at 11 59 34 PM" src="https://user-images.githubusercontent.com/77420992/229408356-6d945085-22ed-4e31-b716-3e9f67efcaf8.png">
Play around with design

**Comment by sophiecra** [comment]
<img width="835" alt="Screen Shot 2023-04-02 at 11 59 51 PM" src="https://user-images.githubusercontent.com/77420992/229408394-c3e2581a-0f16-48a5-9656-483d49f0f0ab.png">
Make compact

**Comment by sophiecra** [comment]
<img width="308" alt="Screen Shot 2023-04-03 at 12 01 10 AM" src="https://user-images.githubusercontent.com/77420992/229408522-674a2299-fc74-48e5-a12e-54a83775f142.png">

**Comment by sophiecra** [comment]
<img width="360" alt="Screen Shot 2023-04-03 at 12 01 43 AM" src="https://user-images.githubusercontent.com/77420992/229408576-d75df883-25b3-4e2b-be5e-ab2fcb3e96a9.png">
Should be <p> instead of card?

**Comment by sophiecra** [comment]
<img width="381" alt="Screen Shot 2023-04-13 at 1 17 18 PM" src="https://user-images.githubusercontent.com/77420992/231835672-dcac3205-8d0a-4437-97d0-a03bf1f930f9.png">
search bar width

**Comment by cravend** [comment]
@sophiecra can you make a new issue with all the screenshots that we haven't fixed yet?

**Comment by claycrews2002** [comment]
![Screenshot 2023-04-22 at 11 17 33 AM](https://user-images.githubusercontent.com/37126723/233792805-ab959cbe-545d-447e-91c5-2cdba140646f.png)

Spacing on all headings on search results

**Comment by cravend** [comment]
Closed by #407
