### ISSUE TITLE
Tell user that they need special permission

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/DKMS#320]
I just created a new free account, but it won't work. The premium account you emailed did work.

https://user-images.githubusercontent.com/228704/230513823-b2c982d2-8bae-4b44-8d33-68b56bde8378.mp4

**Comment by cravend** [comment]
Unfortunately, Spotify requires us to manually whitelist any accounts — otherwise, they can't use the API. There's a way to apply to remove this limit, but they expressly said that they do not approve school projects. If you want, I can whitelist the new account that you made.

**Comment by cravend** [comment]
https://developer.spotify.com/documentation/web-api/concepts/quota-modes

**Comment by josemvidal** [comment]
Tell this to the user in the login page: "Note that we first have to whitelist you..."
