### ISSUE TITLE
On some clicks the app loses the right-side bar

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/DKMS#324]
I click on "Quality Control" and the right-side bar goes away, but not when I click on "George Ezra".

Also, click on "Menace" loads spotify on current frame. Load it on a new frame.

https://user-images.githubusercontent.com/228704/230516691-283273fb-a10f-488b-8a14-f584ef1cc25d.mp4

**Comment by cravend** [comment]
Task transferred to @cravend because of an internal deadline missed by @masondjoseph
