### ISSUE TITLE
Search suggestions

### ISSUE THREAD

**Issue by JPSharp** [SCCapstone/DKMS#328]
While the user is typing a list of search suggestions should populate below the search bar.

https://user-images.githubusercontent.com/44646798/230618882-581fa8f3-4a35-422d-8924-7c6077a4a223.mp4

**Comment by cravend** [comment]
Unfortunately, we've already ran into issues with Spotify rate limiting our API calls, and adding continuous debounced search is likely to magnify that issue. If we have time, we'll play with implementing this and see how the API handles it, but for right now I'll close this.
