### ISSUE TITLE
Can't Change Privacy Settings Back To Public

### ISSUE THREAD

**Issue by jackiehdinh** [SCCapstone/DKMS#334]
After clicking the button to turn off currently public, you can't change it back.

https://user-images.githubusercontent.com/89161210/230754790-cf7ae9f2-9c71-4b2f-8230-4e4f2b700a41.mp4

Steps to Reproduce
- Login and navigate to Settings tab
- Click button next to currently public
- Note: refreshing will reset back to Currently public

**Comment by cravend** [comment]
dev notes: also probably a caching issue

**Comment by sophiecra** [comment]
Already fixed
