### ISSUE TITLE
Feed and Discover Page are the Same Page

### ISSUE THREAD

**Issue by jackiehdinh** [SCCapstone/DKMS#335]
Content of the Feed and Discover pages is the same; however, the names imply that they should be two different pages.

https://user-images.githubusercontent.com/89161210/230754822-4bcfdb5c-aff7-4e87-8576-c82c2ce8e746.mp4

Steps to Reproduce
- Login; default page is feed
- Changing to Discover page shows the same page

**Comment by cravend** [comment]
dev notes: probably a caching issue, definitely a bug / not intended behavior (feed is supposed to be people you follow and discover is everyone)

**Comment by cravend** [comment]
Actually, I just looked into this — it's just because the account used for testing was friends with everyone who had made a post! As more people start using DKMS, the chance that a user follows _everyone_ will be much lower, so I'm closing this for now.
