### ISSUE TITLE
Clicking play under "similar music" section refreshes the feed.

### ISSUE THREAD

**Issue by jespeer** [SCCapstone/DKMS#342]
https://user-images.githubusercontent.com/70123091/230986274-dad25b0a-f3b3-46cd-81fc-e77b8d382558.mp4

Steps to Reproduce:
Log in
Click on Profile
Click on the play button for a square under the "similar music" section

**Comment by jespeer** [comment]
This same issue is happening in the Recommendations tab under the "recommended songs" and "recommended artists" sections, but not under the "featured playlists" section.

**Comment by cravend** [comment]
dev: this is a caching issue
