### ISSUE TITLE
Playback feature does not work

### ISSUE THREAD

**Issue by jespeer** [SCCapstone/DKMS#343]
https://user-images.githubusercontent.com/70123091/230987809-f39e3e28-85b5-4daf-9b73-00a31f3c28e4.mp4

Steps to Reproduce:
Log in
Click on playback button
Connect to spotify
Try to play a song

**Comment by cravend** [comment]
Hi, just to make sure — we have a known issue about playback not working when a song is not yet playing through Spotify. Does this also happen if you've already started playback somewhere else and then try to pick a song?
