### ISSUE TITLE
Search Bar omits Podcast-Only playlists

### ISSUE THREAD

**Issue by Twofishsticks** [SCCapstone/DKMS#355]
While searching for a podcast, the search results may sometimes omit results that are shown within the Spotify app. 

https://user-images.githubusercontent.com/70028633/232335084-01c0a802-b225-4a46-b2f0-1b44f0bac55b.mp4

Steps to Reproduce: 

- Navigate to the search bar in both the Spotify app and DKMS
- Type in "podcast" to both searches 
- Compare Results, specifically with the playlists portion.

**Comment by claycrews2002** [comment]
We will not be adding support for podcasts in DKMS and a podcast will not be displayed when searched for in DKMS. If a podcast is present in a playlist, it will be removed from being displayed on the DKMS playlist page and an alert will be displayed notifying the user of the lack of podcast episodes in the current playlist.
