### ISSUE TITLE
Share to feed - long comments don't work

### ISSUE THREAD

**Issue by danielViolist** [SCCapstone/DKMS#363]
![image](https://user-images.githubusercontent.com/20631276/232343336-c675608f-ba42-49f0-95d9-6097a18518ea.png)

When posting about a song (using the "Share to feed" button), long comments will cause the site to perpetually load. The comment I made was thousands of characters long. Perhaps a character limit. 

![image](https://user-images.githubusercontent.com/20631276/232343349-5a02f8bd-f229-4050-9b02-75afc640153f.png)

**Comment by cravend** [comment]
Duplicate of #359
