### ISSUE TITLE
Honor Thesis Signature

### ISSUE THREAD

**Issue by cravend** [SCCapstone/DKMS#408]
[Dalton Craven Senior Thesis Title Page.pdf](https://github.com/SCCapstone/DKMS/files/11312824/Dalton.Craven.Senior.Thesis.Title.Page.pdf)
Here's the title page of my thesis. Putting some more polish on the contents and then I'll upload it here.

**Comment by cravend** [comment]
[Dalton Craven Senior Thesis v2.pdf](https://github.com/SCCapstone/DKMS/files/11313919/Dalton.Craven.Senior.Thesis.v2.pdf)
@josemvidal, here's the final thesis!

**Comment by josemvidal** [comment]
[Dalton.Craven.Senior.Thesis.Title.Page.pdf](https://github.com/SCCapstone/DKMS/files/11315378/Dalton.Craven.Senior.Thesis.Title.Page.pdf)
