### ISSUE TITLE
Weekly report 2023-04-24

### ISSUE THREAD

**Issue by cravend** [SCCapstone/DKMS#409]

**Comment by sophiecra** [comment]
- #405 
- #389 
- #379 
- #378

**Comment by knguyen423** [comment]
- #362 
- Demo Video

**Comment by masondjoseph** [comment]
- https://github.com/SCCapstone/DKMS/issues/324
- https://github.com/SCCapstone/DKMS/pull/384
- Demo Video

**Comment by claycrews2002** [comment]
- #397 
- #377 
- #378 
- #376 
- #375 
- Demo Video
