### ISSUE TITLE
Prepare for Vercel sponsorship

### ISSUE THREAD

**Issue by cravend** [SCCapstone/DKMS#61]
Rather than paying for a Vercel pro plan, we can try to [get them to sponsor us](https://vercel.com/guides/can-vercel-sponsor-my-open-source-project) as an education / OSS project.

Sponsorship requirements:

- [x] The project should be non-commercial.
- [x] The project should be open source.
- [x] A Vercel banner in the footer of each site page.
- [x] A Vercel banner in the source repository's README.md file.
- [x] All links back to Vercel should use a UTM tag with the format: ?utm_source=[team-name]&utm_campaign=oss.

---

@josemvidal, are there any rules regarding the visibility of our repo? Is it ok if I make it public to meet their requirements? I already have admin access, just wanted to check first.

**Comment by josemvidal** [comment]
When you git-commit code that is for Issue #X, write "#X" (no quotes) somewhere on the commit message. This way, github will automatically add a hyperlink to that commit on that Issue, even if the commit is currently on your Issue branch.
